---
  - name: Config ELK VM with Docker
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:

    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    - name: install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: install pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install python docker module
      pip: 
        name: docker
        state: present

    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
